### ISSUE TITLE
Research SMS Providers for 2FA

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#109]
Research SMS provides for 2FA taking into account these criteria:

- Developer experience
- Technical feasibility
- Technical support
- Costs

Recommendations to look at: Twilio, AWS. etc.

**EXIT CRITERIA:**

- [x] Small Wiki documenting pros & cons of a various providers + a final recommendation with rationale

**Comment by mistryrn** [comment]
Update May 30 2024: WIP wiki page created https://wiki.oicr.on.ca/x/VAEcE

**Comment by b-f-chan** [comment]
@anncatton to take over --> Outstanding research is assessing the top 2 options and picking/recommending one

**Comment by b-f-chan** [comment]
Finished, closing
