### ISSUE TITLE
Add Swagger routers to all services

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#116]
Using the `SwaggerRouter` in the `consent-api` service routers folder as a template, add swagger routers to the remaining API services:

- [x] Consent DAS
- [x] Keys DAS
- [x] PI DAS
- [x] PHI DAS
- [x] Data Mapper

Then add to the express app as is done here https://github.com/OHCRN/platform/blob/develop/apps/consent-api/src/index.ts#L48 , using the `/api-docs` path for consistent endpoint names in each service.

These will require 2 dependencies to be removed from the `consent-api` deps, and installed in the top level package.json:
[Swagger JSDoc](https://www.npmjs.com/package/swagger-jsdoc)
[Swagger UI Express](https://www.npmjs.com/package/swagger-ui-express)

Plus their corresponding types dependencies:
`@types/swagger-jsdoc`
`@types/swagger-ui-express`

Each router file will require the `@openapi` doc at the top of the file to be configured in the swagger, as found in this example: https://github.com/OHCRN/platform/blob/develop/apps/consent-api/src/routers/participants.ts#L29

Exit Criteria:
- [x] Each service has a swagger ui available at `https://localhost:<port>/api-docs`
- [x] Available JSDocs for each endpoint display correctly. No need to add JSDocs for the router endpoints that still need to be implemented in other tickets

**Comment by b-f-chan** [comment]
Merged, closing
