### ISSUE TITLE
Setup LINTER for Custom NextJS App for Enrolment Portal

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#13]
Customize the default NextJS app for the OHCRN Enrolment Portal

- [ ] Add linter, prettier, other tools required
- [ ] Setup directory structure for components and utils as required

**Comment by b-f-chan** [comment]
Adding @anncatton jointly to this ticket to investigate while @mistryrn is away

**Comment by b-f-chan** [comment]
@anncatton will familiarize herself with Next13 --> May need to touch base with Rakesh.  Just create container for webapp and set to NOT default

**Comment by anncatton** [comment]
added `prettier` in #18

**Comment by b-f-chan** [comment]
@mistryrn - To take time this sprint to take a stab at the linter

**Comment by b-f-chan** [comment]
@mistryrn - Please aim to close this one off before starting Data Model implementation

**Comment by b-f-chan** [comment]
Merged, closing
