### ISSUE TITLE
Create Layout for Participant Self-Registration Page

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#151]
Create layout (no forms or logic) for Participant Self-Registration Page:

- [ ] Implement all elements/components except the Form

**Expected Outcome(s):**

- [ ] Responsive layout that matches the mockup and design system
- [x] Basically the whole screen with nav, buttons, header/footer, **but no forms/fields/logic**

**Comment by samrichca** [comment]
additional tickets

- https://github.com/OHCRN/platform/issues/359 add login link

**Comment by b-f-chan** [comment]
We will merge this for now so it's not blocked, and @samrichca will make follow-up ticket to integrate the controls

**Comment by samrichca** [comment]
scope update:

- add the form, but without radio or date inputs

**Comment by b-f-chan** [comment]
Let's review and merge what we have

**Comment by samrichca** [comment]
validation notes
- only go to step 2 if user fully successfully completes step 1
- strip values in step 2 inputs if user goes back to step 1
