### ISSUE TITLE
Create Layout for Clinician Invite Page

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#152]
Create layout (no forms or logic) for Clinician Invite Page:

**- [ ] MUST BE DONE AFTER PARTICIPANT SELF-REGISTRATION PAGE**
- [ ] Implement all elements/components except the Form

Expected Outcome(s):

- [ ] Responsive layout that matches the mockup and design system
- [ ] Basically the whole screen with nav, buttons, header/footer, **but no forms/fields/logic**

**Comment by samrichca** [comment]
as part of this ticket, investigate image optimization in figma

**Comment by b-f-chan** [comment]
Ready for testing once QA is available

**Comment by b-f-chan** [comment]
@samrichca can this be closed?
