### ISSUE TITLE
Research E-Signature Plugin Solutions

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#155]
Research various e-signature plugin solutions

Criteria:

- [x] Is it compatible with NextJS 13+?
- [x] Is it open source?
- [x] Does it meet accessibility requirements?
- [x] Is it actively developed/maintained?  How recently was it updated?
- [x] Is it easily customizable (functionality, look 'n feel, copy/verbiage, etc)
- [x] Supports translation?

**Expected Outcome(s)**

- [x] Wiki page summarizing options with a recommendation
- [x] Quick meeting to debrief rest of team on the solution

**Comment by b-f-chan** [comment]
@mistryrn to finish this sprint so we can hand off implementation to @samrichca or @xusandrew

**Comment by b-f-chan** [comment]
@mistryrn to tag reviewers

**Comment by mistryrn** [comment]
Wiki page: https://wiki.oicr.on.ca/display/OHCRN/E-Signature+Implementation+for+OHCRN

**Comment by b-f-chan** [comment]
Wiki page finished, reviewed, Andrew has used to implement
