### ISSUE TITLE
Convert UI localization dictionaries to TS

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#159]
- [ ] convert all UI dictionary files in `i18n/locales` from `.json` to `.ts`
- [ ] add an `as const` assertions to each dictionary
- [ ] update the import statement in the `getTranslation` function in `i18n/hooks/getTranslation` to use the proper file extension
- [ ] where available, update any enum key values to their corresponding zod types, i.e.  `BRETON: 'Breton',` -->`[Ancestry.enum.BRETON]: 'Breton'`. We can convert other enum keys as the zod types are implemented

There will probably be some more changes we can add for type safety, but this ticket is just to get something basic setup.

**Comment by b-f-chan** [comment]
Merged and closed
