### ISSUE TITLE
Setup Localization Toggle Component

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#16]
Setup the UI component for the localization toggle in the top right of the portal header.

This involves more than just creating the component visually, but also adding logic as to how it will operate.

Specifically, do the following:

- [x] Create the localization toggle control
- [ ] ~~Connect the toggle control to this library: https://github.com/i18next/next-i18next~~
- [x] Add the toggle to the header that was established in a previous ticket

**Comment by anncatton** [comment]
Implemented as a simple button to switch between 2 languages only. If more languages are supported in future we will modify accordingly.
