### ISSUE TITLE
Investigate unit testing solutions

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#161]
Problem: Our current unit testing approach (Mocha, Chai, NYC) isn't providing test coverage statistics. We want to find a solution that supports ES modules, TypeScript, and Next.

**Exit criteria:**
- [x] Will Vitest work? Yes, except I wasn't able to get absolute paths working.
- [x] Estimate level of effort to switch: No coding changes needed besides imports.

**Comment by b-f-chan** [comment]
@samrichca - Please complete any PR feedback for this ticket and close off before jumping further into the ReactHook sample page

**Comment by b-f-chan** [comment]
Merged, closing
