### ISSUE TITLE
Build Consent API Endpoint --> Participant Dashboard `GET /wizard/pdf`

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#165]
Build consent API endpoint: `GET /wizard/pdf'

**Applicable Page:** Participant Dashboard
**Functionality:** Download consent form PDF

**Expected Outcome(s):**

- [ ] Swagger doc for the endpoint is functional and testable
- [ ] Unit testing implemented for this endpoint

---

Update 10/30/2023 from Sam: 
- Use a MOCK_USER_ID constant to retrieve data
- For now, send a response with all consent questions & responses. These will be used to generate a PDF later.
- Endpoint mapped out here https://github.com/OHCRN/platform/pull/190

**Comment by samrichca** [comment]
do this ticket when we have all the consent steps mapped, since we need to fetch all questions

**Comment by b-f-chan** [comment]
No longer required, closing, we will include this functionality in the Step 5 GET endpoint

Actual PDF generation will also be handled from UI side so no backend impact
