### ISSUE TITLE
Design Mechanism to Securely and Temporarily Store User Info Before Registration

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#172]
Design mechanism to securely and temporarily store user (Participant) info before registration.

In our current user flow, Participants must supply some basic personal & contact information **BEFORE** registering and creating an actual account.  Hence info must be stored in a temporary and secure way before the actual account is created & registered.

@joneubank and Leo can be resources to consult due to their experience with the auth system in Overture

**Expected Outcome(s):**

- [ ] Wiki page describing our strategy and mechanism for the above

**Comment by anncatton** [comment]
The data mentioned here refers to participant info for our system, not prefilling a registration form.

**Comment by b-f-chan** [comment]
Close, will be incorporated as part of registration design doc
