### ISSUE TITLE
Map Out Consent API Endpoints --> user info

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#174]
Map out the Consent API endpoints & requests needed for the header & navigation, as well as participant dashboard

`GET user`
- 200 status
- full name
- email
- role (e.g. user vs admin)
- email verified status
- 2FA status

[Mockup Link](https://www.figma.com/file/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?type=design&node-id=42-7956&mode=design&t=zMmow2tRA55Olzja-0)

**Expected Outcomes:**

- [ ] Swagger Docs listing the required endpoints/requests --> Can be single Wiki page with different sub-section for each UI page
    - [x] List of specific web requests to be made (e.g. POST)
    - [x] Type of method used
    - [x] Query parameters
    - [x] Message body structure
    - [x] URLs required
    - [x] What validations are needed on API side when request is received
    - [x] Final output --> A ZOD object that encapsulates the BODY of the request (actual code sample)
    - [x] **Document in the Wiki for each endpoint:**
        - [x] Request parameters
        - [x] Request body
        - [x] Response body

**Comment by b-f-chan** [comment]
@alyssadsouza - Please do quick review and indicate whether Jon's feedback applies

**Comment by b-f-chan** [comment]
Merged, closing.  Cleanup tasks will be completed in #236
