### ISSUE TITLE
Add remaining shared enum types to dictionaries

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#180]
The dictionary implementation in [#159](https://github.com/ohcrn/platform/issues/159) uses the enums in the `Types` package as dictionary keys, but some types were outstanding so these will need to be added when available.
- Ancestry
- BirthSex
- GeneticsClinic
- Molecular Lab
- Gender
- HistoryOfCancer
- FamilyHistoryOfCancer

**UPDATE 23/11/07** - after a discussion with the team, dictionaries for enums will not use the enum values as keys, instead each dictionary can be typed using the enum itself as the `Record` key, like so:
```
import { Ancestry } from 'types/entities';
const ancestryDictionary = {
...
} satisfies Record<Ancestry, string>;
```

This will ensure the dictionary keys are aligned with zod types in the `types` package, while still maintaining readability.

- [x] update the above dictionaries using the recommended type pattern
- [x] move `ConsentCategory` from the `common` dictionary to its own dictionary file, and update with this pattern
- [x] move `ConsentGroup` from the `invite` dictionary to its own dictionary file, and update with this pattern
- [x] update the `Province` dictionaries to follow this pattern

**Comment by b-f-chan** [comment]
Merged, closing
