### ISSUE TITLE
Rename consent steps

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#181]
Update naming of consent steps from consentStepX to nameOfPage & add a dictionary to keep track of the order, for better organization & in case we need to update the consent wizard.

## Step 1

Update consent step naming from 

- consent-step-1
- consentStep1Dictionary
- ConsentStep1Component

to 

- informedConsent
- informedConsentDictionary
- InformedConsentComponent

## Step 2

Add a dictionary to track the order of the consent wizard steps for both the UI & API.

## Additional notes

- This name will also be used in the consent API: `wizard/steps/:stepName` => `wizard/steps/informed-consent`
- UX stays the same: The URL path `/consent/step-1/` loads the informed consent page.

**Comment by anncatton** [comment]
Dictionaries renamed in #162 .

**Comment by b-f-chan** [comment]
Closing as duplicate, already handled in #162
