### ISSUE TITLE
Add documentation for Dictionary translation implementation

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#185]
Create a docs file describing how translations have been implemented in the Consent UI. Can use the info in this [PR description ](https://github.com/OHCRN/platform/pull/162), as well as a quick description for:

- [ ] create a file /docs/translations.md
- [ ] how to add new translations to dictionary
- [ ] how to use translations (with information about server-side only)
- [ ] how replacements work for translation templates

Create a `docs` dir so that we have a central folder for various docs by category

**Comment by b-f-chan** [comment]
Merged and close
