### ISSUE TITLE
Create Modal Component

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#187]
Create modal component that will be used throughout the portal with these elements:

- [x] Modal window
- [x] Body with content
- [x] Confirmation control/button with label + action trigger
- [x] Cancel control/button with label + action trigger
- [x] Add/integrate modal to the web app --> Use React Context (ARGO UI Kit is a good example to refer to, talk to @samrichca if required)

Reuse what we can from ARGO project UI kit

**EXPECTED OUTCOME(S):**

- [x] Sample modal with the above elements

**Comment by alyssadsouza** [comment]
@b-f-chan @patrickdsantos the modal is now testable on the register page in QA with:

- responsive styling for mobile + tablet + desktop screen sizes
- ability to close by pressing the `Escape` key or clicking outside the modal card.

**QA Link**

https://consent-ui.dev.ohcrn.cancercollaboratory.org/en/register

**Comment by patrickdsantos** [comment]
Incredible work @alyssadsouza - this looks fantastic! 

Just one piece of feedback, is it possible to apply the dark overlay to the header in mobile and tablet view? 
If it's not possible totally fine we can proceed as is. Thank you!
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK01DQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--521c764d8615d1b3232af15f95bfeac0375ef5a8/Screenshot%202023-11-23%20at%2011.03.32%20AM.png)

**Comment by alyssadsouza** [comment]
@patrickdsantos of course! that's a simple fix I'll make the change

**Comment by b-f-chan** [comment]
Done, closing
