### ISSUE TITLE
Create Banner Component

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#188]
Create banner component that is used for maintenance and system downtime messages

**MOCKUP LINKS:**

Critical Banner:
https://www.figma.com/file/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?type=design&node-id=3084-16154&mode=design&t=9dYOqqQs3WIqbh77-0

Warning Banner:
https://www.figma.com/file/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?type=design&node-id=3084-15819&mode=design&t=9dYOqqQs3WIqbh77-0

Info Banner:
https://www.figma.com/file/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?type=design&node-id=3084-15471&mode=design&t=9dYOqqQs3WIqbh77-0

Multiple Banners:
https://www.figma.com/file/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?type=design&node-id=3084-16521&mode=design&t=9dYOqqQs3WIqbh77-0

**EXPECTED OUTCOME(S):**

- [ ] Sample banner component on a web page
- [ ] Ability to show multiple banners at once
- [ ] Banners must be controlled through environment variables
- [ ] Option to make them dismissable (or not)
- [ ] Different styling options/variants
    - [ ] Informational
    - [ ] Warning
    - [ ] Critical
 - [ ] Ability to add copy below the title
 - [ ] Ability to inject HTML

**Comment by b-f-chan** [comment]
@patrickdsantos - We need some mockups for this first

**Comment by patrickdsantos** [comment]
Questions:
- is this for participant portal or CRC dashboard? Or both?
- What does environment variables mean?
- Does the styling have to differ from current banner designs?
- Average length of copy?

**Comment by b-f-chan** [comment]
Creating separate ticket for mockups

**Comment by b-f-chan** [comment]
To be tested

**Comment by b-f-chan** [comment]
Will test as part of other tickets, closing
