### ISSUE TITLE
Hook Up Notifications to Dashboard Page

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#189]
Hook up notifications to the Participant dashboard, including these tasks:

- [ ] Setup reusable context for notifications with reusable hook to trigger
- [ ] Ability to trigger notifications conditionally with specific parameters (titles, actions, category, etc)
- [ ] Create the following examples:
    - [ ] One notification at the top of the page (e.g. form success)
    - [ ] One notification that is localized to an area of the page (e.g. Captcha error)

All work done here must be reusable on OTHER pages, not just for the Dashboard specifically

Possibly look at ARGO and/or HCMI for examples of how to do this

**NOTE:** Notification category for example is informational, warning, critical, etc.

**EXPECTED OUTCOME(S):**

- [ ] Display a notification on the dashboard for the scenario where you didn't verify your email
- [ ] Display notification on fake recaptcha page (this is a localized notification that uses Hook instead of context)

**Comment by samrichca** [comment]
updated scope:
- **notification triggered by routing:**
  - click a button on the homepage
  - update notification context
  - redirect to dashboard
  - show "consent completed" notification
  - this is meant to imitate completing the consent wizard
- **notification triggered by user info:**
  - request user info
  - if consent is in progress, show "review consents in progress" notification
- **notification triggered by URL search params:**
  - check if URL contains ?registered=true
  - show "thanks for registering" notification

the recaptcha error notification is a small static error message and doesn't require hook/context scaffolding.

**Comment by b-f-chan** [comment]
@samrichca can this be closed?
