### ISSUE TITLE
Add ZOD Schema Changes for Data Model v4.0

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#194]
Need to update ZOD schemas (`types` package) to account for latest changes in Data Model v4.0.  Some missed changes from v3.0 may also be included.

As summarized from ticket #163:

   - [x] Update `ParticipantIdentification`
     - [x] Change `participant_preferred_name` to optional in `Participant` table
     - [x] Change `consent_group` to required in `Participant` table
   - [x] Update `ClinicalProfile`
     - [x] Remove `genetics_clinic_visited` field
     - [x] Add new optional fields to `ClinicalProfile` table:
       - [x] `self_reported_clinician_first_name`
       - [x] `self_reported_clinician_last_name`
       - [x] `self_reported_clinician_title_or_role`
       - [x] `self_reported_genetics_clinic_visited`
       - [x] `self_reported_molecular_clinic_visited`
   - [x] Update `OhipNumber`
     - [x] Update regex for `ohip_number` field to accept special code `0000000000` (10 zeroes)
   - [x] Update unit tests

**Comment by alyssadsouza** [comment]
Note that 10 zeros is already acceptable for the `ohip_number` field, which just lists its permissable values as 10 digits.

**Comment by b-f-chan** [comment]
Merged, closing
