### ISSUE TITLE
PHI DAS: Add PRISMA Schema Changes for Data Model v4.0

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#197]
Need to update PRISMA schemas for the PHI DAS to account for latest changes in Data Model v4.0.  Some missed changes from v3.0 may also be included.

Changes as summarized in ticket #163:

- [x] Remove `genetics_clinic` field
- [x] Add new optional fields to `ClinicalProfile` table:
   - [x] `self_reported_clinician_first_name`
   - [x] `self_reported_clinician_last_name`
   - [x] `self_reported_clinician_title_or_role`
   - [x] `self_reported_genetics_clinic_visited`
   - [x] `self_reported_molecular_clinic_visited`
- [x] update seed data
- [x] update jsdocs, create service function to reflect changes

**Comment by alyssadsouza** [comment]
Changed `self_reported_molecular_clinic_visited` to `self_reported_molecular_lab_visited` as per @b-f-chan's directions

**Comment by b-f-chan** [comment]
Merged, closing
