### ISSUE TITLE
Map Out Consent API Endpoints --> Consent Wizard Step 4

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#204]
Map out the Consent API endpoints & requests needed for the Consent Wizard Step 4 Consent to Recontact

[Mockup Link](https://www.figma.com/proto/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?type=design&node-id=41-13068&t=HldMEc19CwIOzLdo-0&scaling=min-zoom&page-id=2%3A11926)

**Expected Outcomes:**

- [ ] Swagger Docs listing the required endpoints/requests --> Can be single Wiki page with different sub-section for each UI page
    - [ ] List of specific web requests to be made (e.g. POST)
    - [ ] Type of method used
    - [ ] Query parameters
    - [ ] Message body structure
    - [ ] URLs required
    - [ ] What validations are needed on API side when request is received
    - [ ] Final output --> A ZOD object that encapsulates the BODY of the request (actual code sample)
    - [ ] **Document in the Wiki for each endpoint:**
        - [ ] Request parameters
        - [ ] Request body
        - [ ] Response body

**Comment by b-f-chan** [comment]
Assigning to @alyssadsouza as agreed to finish design & PR review

**Comment by b-f-chan** [comment]
Merged, closing
