### ISSUE TITLE
Consent DAS: Add PRISMA Schema Changes for Participant Lifecycle Fields

### ISSUE THREAD

**Issue by mistryrn** [OHCRN/platform#218]
Need to update PRISMA schemas for the Consent DAS to account for Participant Lifecycle fields that need to be added

## Consent DAS Prisma changes for Participant Lifecycle

- [x] create new enum for `LifecycleState` with the following values:
  - [x] `REGISTERED`
  - [x] `CONSENTED`
  - [x] `IN_PROCESSING`
  - [x] `PROFILE_COMPLETE`
  - [x] `PUBLISHED`
  - [x] `DELETION_REQUESTED`
  - [x] `PAUSE_REQUESTED`
  - [x] `CHANGE_REQUESTED`
  - [x] `APPROVED_FOR_DELETION`
  - [x] `PAUSED`
  - [x] `DELETED`
- [x] add `currentLifecycleState` to `Participant` Prisma model in `consent-das`, of type `LifecycleState` (required, will default to `REGISTERED` on creation)
- [x] add `previousLifecycleState` to `Participant` Prisma model in `consent-das` of type `LifecycleState` (optional)
- [x] update relevant seed data, routers, services, etc within the `consent-das` (note: JSDocs in routers may require related changes in Zod schemas from https://github.com/OHCRN/platform/issues/198)

**Comment by b-f-chan** [comment]
Merged and closing
