### ISSUE TITLE
Build Data Mapper Endpoint --> Clinician Invite Page: `POST /invites`

### ISSUE THREAD

**Issue by mistryrn** [OHCRN/platform#234]
Build corresponding `POST` endpoint in the `data-mapper` to consume the validated Clinician Invite Request (currently known as `ClinicianInviteForm`) coming from `consent-api` and send it to the relevant DASes to create a new Clinician Invite.

## DAS Breakdown
The data coming from the request should be validated and then sent to the appropriate DASes as follows:

### PI DAS
- Clinician Invites table
	- participantFirstName
	- participantLastName
	- participantEmailAddress
	- participantPhoneNumber
	- participantPreferredName
	- guardianName
	- guardianPhoneNumber
	- guardianEmailAddress
	- guardianRelationship

### Consent DAS
- Clinician Invites table
	- inviteSentDate
	- inviteAcceptedDate
	- inviteAccepted
	- clinicianFirstName
	- clinicianLastName
	- clinicianInstitutionalEmailAddress
	- clinicianTitleOrRole
	- consentGroup
	- consentToBeContacted

## Data Mapper Breakdown
- Add a `createInvite` service to the `services` directory
- Add an `invites.ts` router to the `routers` directory

## Order of Operations
1. In the `PI DAS`, create a Clinician Invite with the data outlined in the DAS Breakdown. Get the new `Invite ID` from the result of this.
2. In the `Consent DAS`, create a Clinician Invite with the data outlined in the DAS Breakdown, passing in the `Invite ID` from Step 1.

## Success Response
TBD -- 201 with the inviteID? @anncatton and @mistryrn to follow up

## Other Areas to Investigate

Strategy on how to approach the following:

- [ ] Logging
- [ ] Error Handling
- [ ] Validation

**Comment by b-f-chan** [comment]
Merged, closing
