### ISSUE TITLE
Clean Up Consent API Endpoints

### ISSUE THREAD

**Issue by alyssadsouza** [OHCRN/platform#236]
Based on feedback from @joneubank on mapping out the Consent Wizard steps endpoints, these will need to be cleaned up at implementation time:

| Router | Remove redundant logs | 400 response for bad requests | Remove unnecessary enums | Prune unit tests |
| --- | --- | --- | --- | --- |
| `informedConsent.ts` |  |  | ✔️ | ✔️ |
| `invites.ts` |  |  | ✔️ | ✔️ |
| `status.ts` |  | ✔️ | ✔️ | ✔️ |
| `user.ts` |  | ✔️ | * TBD: `UserRole` enum | ✔️ |
| `wizard.ts` |  | ✔️ | ✔️ | ✔️ |

Some notes:

**Logging**

- We’ll use a library to handle logging requests https://npmjs.org/package/morgan
- Keep error logs for now

**Error handling**

- We’ll consider error handling middleware
- For now just make sure if data is being parsed/validated explicitly in the endpoint, it should return the appropriate 400 response if the request was invalid

**Enums**

- We don’t need these for UI form fields, they’re more useful for data model fields, etc

**Unit tests**

- Organize unit tests into more descriptive test cases so it’s clear what is changing and being tested for
- We don’t need to test Zod’s validation, test for specific validation/`refine()` logic or regex that is custom

**Comment by alyssadsouza** [comment]
Will open a PR to clean up the unit tests and link here

**Comment by b-f-chan** [comment]
Merged, closing
