### ISSUE TITLE
Build Data Mapper Endpoint --> Clinician Invite Page: `GET /invites/:inviteId`

### ISSUE THREAD

**Issue by mistryrn** [OHCRN/platform#253]
Build corresponding `GET` endpoint in the `data-mapper` to retrieve a Clinician Invite for consumption by `consent-api` from the relevant DASes and serve as a full Zod Clinician Invite.

## DAS Breakdown
- PI DAS
    - [x] ClinicianInvite
- Consent DAS
    - [x] ClinicianInvite

## Data Mapper Breakdown
- [x] Add a `getInvite` service to the `services` directory

## Order of Operations
1. Get the ClinicianInvite for the invite ID passed as a prop to `getInvite` from the PI DAS
2. Get the ClinicianInvite for the invite ID passed as a prop to `getInvite` from the Consent DAS
3. Combine into a Zod Clinician Invite
4. Serve in the response

## Success Response
`200` containing the Clinician Invite object

## Other Considerations
Highlight areas that may need the following:
- Logging
- Error Handling
- Validation

**Comment by b-f-chan** [comment]
Done, closing
