### ISSUE TITLE
Build Data Mapper Endpoint --> Participant Self-Registration Page: `POST /register`

### ISSUE THREAD

**Issue by mistryrn** [OHCRN/platform#254]
Build corresponding `POST` endpoint in the `data-mapper` to consume the validated Participant Registration coming from `consent-api` and send it to the relevant DASes to create a new Participant.

## DAS Breakdown
- PI DAS
    - [ ] Participant
- Consent DAS
    - [ ] Participant

## Data Mapper Breakdown
- [ ] Update the `createParticipant` service in the `services` directory

## Order of Operations
1. In the `PI DAS`, create a Participant with the data outlined in the DAS Breakdown. Get the new `Participant ID` from the result of this.
2. In the `Consent DAS`, create a Participant with the data outlined in the DAS Breakdown, passing in the `Participant ID` from Step 1.

## Success Response
`201` containing the data TBD

## Other Tasks
Implement the following areas that may be needed:

- [ ] Logging
- [ ] Error Handling
- [ ] Validation

**Comment by b-f-chan** [comment]
@anncatton - Can this be closed?

**Comment by b-f-chan** [comment]
Finished, closing
