### ISSUE TITLE
Add function to translate entire namespace

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#313]
Add a function that translates an entire namespace, with parameters.

## Exit Criteria

A function similar to `translate()` that

- returns an entire namespace's translations, in an object
- accepts parameters to replace parts of the translated string(s)

e.g.

```
translateAll('myTranslationNamespace', { translationKey: { year: "2023" }});

/// result

{
  translationKey: "This text was translated in the year 2023.",
}
```

**Comment by b-f-chan** [comment]
Do during translation sprint before launch

**Comment by b-f-chan** [comment]
Merged, closing
