### ISSUE TITLE
Clean up Server Errors with a `ServerErrorResponse` type

### ISSUE THREAD

**Issue by alyssadsouza** [OHCRN/platform#321]
In the shared types package `types/httpResponses` directory, add a `ServerErrorResponse` (similar to the `NotFoundErrorResponse`) which returns an `ErrorResponse` with the `error` set to `SERVER_ERROR` from the `ErrorName` enum. Additonally, replace all server errors currently being returned in routers (across Consent API, Data Mapper, and the DAS) with this type instead.

**Expected Outcome(s)**
- [x] `ServerErrorResponse` added to the `types/httpResponses` directory
- [x] All server errors in our routers are instances of the `ServerError`

**Comment by b-f-chan** [comment]
Done, closing
