### ISSUE TITLE
Add Embedded PDF Viewer to Consent Wizard Step 1

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#329]
Here's the sample PDF to be embedded in the viewer

[OHCRN_Main_Consent_Form-REB-clean_v2_5Jan2024.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0ZWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ea1118344b9ab274685d0a7e737974d75cc3453/OHCRN_Main_Consent_Form-REB-clean_v2_5Jan2024.pdf)

**Comment by b-f-chan** [comment]
@patrickdsantos - Need mockup for download button on mobile

**Comment by patrickdsantos** [comment]
mocks have been updated with download button! <img width="439" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNC9hQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c708b499c9a843c20abc6b0771d0f3106c4b245/Screenshot%202024-01-17%20at%204.50.07%20PM.png" alt="Screenshot 2024-01-17 at 4.50.07 PM.png" />

**Comment by samrichca** [comment]
I suggest postponing this until we can test a draft PDF (not a placeholder) in a QA environment in multiple browsers and devices.

**Comment by xusandrew** [comment]
@b-f-chan is there a french version of the sample pdf?

**Comment by b-f-chan** [comment]
Reviewed & merged --> Closing
