### ISSUE TITLE
Implement Actual Routes for Web App

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#33]
Add the actual routes for the web app to each page

Dependency --> @b-f-chan and @patrickdsantos to provide route names

- Homepage: https://registry.ohcrn.ca
- Participant Registration: https://registry.ohcrn.ca/en/participant/registration
- Participant Keycloak Create Account: https://keycloak.ohcrn.ca/auth/realms/virusseq/login-actions/registration
- Clinician Patient Registration : https://registry.ohcrn.ca/en/clinician/registration
- Participant Dashboard: https://registry.ohcrn.ca/en/participant/dashboard
- Consent Wizard: https://registry.ohcrn.ca/en/participant/consent-forms
    - For the consent wizard's five steps, we will not use separate paths for each, rather, we have agreed as a team to use parameters in the URL for steps 1 to 5; the parameters will simply be named step-1, step-2, step-3, step-4, step-5, rather than the entire name of the step which can be long

@anncatton - Not sure if Keycloak manages its redirected URLs and if we need `/en` and `/participant` for these routes

**NOTE:** We may need more routes added later when we flesh out auxiliary functions like Change Password, Change Email, Update Consent, Withdraw Consent, etc.

**Comment by anncatton** [comment]
Will handle the form step paths in #34

**Comment by b-f-chan** [comment]
Merged, closing

**Comment by b-f-chan** [comment]
We will create a separate ticket to revise and simplify the URLs

-
