### ISSUE TITLE
Add Radio Button Component

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#347]
Add a reusable REACT radio button selection component that can be reused in the UI

i.e. for optional consent selections on Step 3 & 4 of consent wizard

@samrichca to add any details required

---

- Make a stub form on an unused page (form context is needed to create an input)
- Create a new input component for radio buttons
  - Use checkboxes as an example
- Add a new fieldset for radio buttons
- Add disabled & error states

**Comment by mahesh2504** [comment]
i can work on this issue, can you assign it to me @b-f-chan

**Comment by b-f-chan** [comment]
@xusandrew can this be closed?

**Comment by xusandrew** [comment]
@b-f-chan yes

**Comment by b-f-chan** [comment]
Reviewed & merged --> Closing
