### ISSUE TITLE
Add Special UI Component for OHIP Field

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#348]
Add a special UI component to handle the OHIP field on Step 2 of the Consent Wizard

This is a custom component where there is a text field with an associated checkbox input that has conditional logic

Please see mockups for reference

@samrichca to add any details required

---

- Make a stub form on an unused page that will eventually use this component (form context is needed to create an input)
- I don't think any new input components are required
- Add a new fieldset for a text input that can be disabled with a checkbox
- Add disabled & error states

**Comment by chelseagmarie** [comment]
Hi, where is it possible to find the mockups to reference for this issue?

**Comment by xusandrew** [comment]
blocked - need flag for if the OHIP field disabled/enabled in data model

**Comment by b-f-chan** [comment]
Merged, closing
