### ISSUE TITLE
Add Component for Info Cards on Step 5 of Consent Wizard

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#349]
Add a new/custom UI component for the small informational cards on Step 5 of the consent wizard

See mockups for reference

@samrichca to add any details required

**Comment by xusandrew** [comment]
Next steps:
Add UI for fields that are empty (ex -- means empty field)
Add prop to choose between green/grey box

**Comment by b-f-chan** [comment]
still in review

**Comment by b-f-chan** [comment]
@xusandrew can this be closed?

**Comment by xusandrew** [comment]
@b-f-chan yes

**Comment by b-f-chan** [comment]
Reviewed & merged --> Closing
