### ISSUE TITLE
Forms: Update tooltip

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#357]
Update the design/functionality of the tooltip. TBA

@patrickdsantos to provide link to latest mockups when ready

**Comment by patrickdsantos** [comment]
link to the mocks: https://www.figma.com/file/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?type=design&node-id=41%3A12990&mode=design&t=dx8bjY29tJcgWV3x-1

**Comment by b-f-chan** [comment]
@xusandrew can this be closed?

**Comment by xusandrew** [comment]
@b-f-chan yes

**Comment by b-f-chan** [comment]
Reviewed & merged --> Closing
