### ISSUE TITLE
Register page: Add login link

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#359]
Currently on the Registration page, there's a Login button at the top right that takes the user to the homepage.

When a login link is available, add it to the external URLs constants file and this button.

Exit Criteria:
- When a user is on the Register page and clicks on the Login button, they'll go to the Login page.

## Blocked

We don't have a login link yet.

**Comment by anncatton** [comment]
This should just use the `LoginButton` component, which will trigger the signIn event for Keycloak
