### ISSUE TITLE
Consent Wizard: Progress header items don't have a unique key

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#362]
In apps/consent-ui/src/components/common/ProgressHeader/index.tsx on line 49, the `map` returns a fragment, which doesn't have a unique key. This generates a "Warning: Each child in a list should have a unique "key" prop." error in the terminal. Converting the fragment to a div with a unique key breaks the CSS.

- Change the fragment to a div with a unique key
- Fix the resulting CSS issues

Exit Criteria:
- Page looks exactly like it does now
- Unique key error is resolved

**Comment by b-f-chan** [comment]
@xusandrew can this be closed?

**Comment by xusandrew** [comment]
@b-f-chan yes

**Comment by b-f-chan** [comment]
Reviewed & merged --> Closing
