### ISSUE TITLE
Register Form: Implement radio & date inputs

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#366]
Currently in the registration form there are placeholders for the radio & date inputs, because these inputs haven't been built yet.

- Add radio input to "are you registering on behalf of someone else" field
- Add date input to "date of birth" field
- Update type & Zod schema for the form
  - This isn't implemented in types/consentApi yet, so continue to use the stubs in the UI.
- Make sure the form works
- Make substitute decision maker fields optional depending on radio input values
- Show "this participant is a minor" modal depending on date of birth selected

Exit Criteria:
- Form has radio inputs for the first question
- Form has a date input for date of birth
- If the user decides to use a substitute decision maker, show the fields for substitute decision maker info
- If the user enters a date of birth for a participant younger than 18, show a modal directing them to talk to a clinician

## Blocked

- Radio & date inputs not done
- Register form not done

**Comment by b-f-chan** [comment]
Component PRs reviewed, fixed, merged this ticket is no longer blocked, removing label

**Comment by b-f-chan** [comment]
Will open PR for date portion of this and wait to add Guardian fields later

**Comment by samrichca** [comment]
Separate ticket for modal https://github.com/OHCRN/platform/issues/456
