### ISSUE TITLE
Consent Wizard Step 1: Informed Consent: Add PDF download

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#379]
When the "study information and informed consent" PDF is available, add it to 

- Consent Wizard Step 1: Informed Consent
  - Link in text at the top of the page
  - Download button on mobile/tablet
  - PDF viewer on desktop
  - /src/public folder in consent-ui
 
Exit Criteria:
- User goes to Consent Wizard Step 1: Informed Consent
- User can download this PDF from a link in the text at the top of the page
- User can download this PDF by clicking on a download button, on mobile/tablet
- User can view the PDF in a PDF viewer on desktop
- **NOTE:** Leave French placeholder for now, no need to handle until translated version is available

Attached is the sample PDF that will be embedded in the viewer and downloadable:
[OHCRN_Main_Consent_Form-REB-clean_v2_5Jan2024.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1ZWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef8b05bc21c1e1581afabd98288f79f55d2ab35a/OHCRN_Main_Consent_Form-REB-clean_v2_5Jan2024.pdf)

**Comment by b-f-chan** [comment]
@b-f-chan to get file for @samrichca and that should unblock this ticket

**Comment by samrichca** [comment]
blocked because we don't have object storage

**Comment by b-f-chan** [comment]
This is unblocked, as we can keep the PDF in the GitHub repo

**Comment by b-f-chan** [comment]
Closing, will be done as sub-task within #460
