### ISSUE TITLE
Register page: Improve form validation

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#382]
Currently the form gets validated on submit. Change to validating on blur.

- Disable submit button by default
- When editing the form
  - On blur (when leaving a field) validate the form.
  - Don't indicate "empty field" warnings to the user. Only show warnings on dirty fields.
  - Enable the submit button if the form is valid
  - Retain validation on submit just in case

### Next/back buttons

- Next:
  - Enable when the fields in step 1 are complete and valid
- Back:
  - Don't save users' input
    - If some fields are dirty, warn the users they'll lose their input by going to the previous step

**Comment by b-f-chan** [comment]
Has been implemented, closing
