### ISSUE TITLE
Consent UI: Move public folder to root folder

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#384]
Currently the `/public` folder is inside the `/src` folder, and files in the public folder can't be accessed directly (http://localhost:3000/placeholder.pdf returns a 404). I tested the issue in isolation in a basic Next app & moving the public folder to root resolves the issue.

According to the Next docs, the public folder should be in the root folder [1](https://nextjs.org/docs/app/building-your-application/configuring/src-directory) [2](https://nextjs.org/docs/app/building-your-application/optimizing/static-assets).

- Move public folder to root
- Make a /public/assets folder (`assets` is already exempt from i18n routing middleware)
- Move images & PDFs to /public/assets/images and /public/assets/pdfs
- Update imports where needed

Exit Criteria
- Images & page routing still work
- http://localhost:3000/placeholder.pdf displays a PDF

**Comment by b-f-chan** [comment]
@samrichca can this be closed?
