### ISSUE TITLE
Open questions - Participant Registration

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#388]
Just to track some questions that have come up during work on #254:

- (1) `residentialPostalCode` is a required field in both PI-DAS Participant and the `ParticipantIdentity` schema, is this correct? If so, it will need to be included in the registration form
- (2) `consentToBeContacted` is part of the registration flow, but is currently stored in the Consent-DAS `ClinicianInvite` table only. It will need to be added to the Consent-DAS `Participant` table as well, to account for users who self-register without an invite
- (3) need to verify if guardian info fields and participant contact info fields (`participantEmailAddress`, `participantPhoneNumber`) will be mutually exclusive. This will affect how the schema validations are handled, and would also require these latter fields to be made optional in the PI-DAS `Participant` table.
- (4) `phoneNumber` and `emailAddress` in the PI-DAS `Participant` table should be changed to `participantEmailAddress` and `participantPhoneNumber` for clarity
- (5) In PI-DAS, the `ClinicianInvite` table has `participantFirstName` and `participantLastName`, whereas the `Participant` table has `participantOhipFirstName` and `participantOhipLastName`. Was this intentional?

**Comment by b-f-chan** [comment]
(1) Yes, residential postal code should not be required to create the initial participant in the Registered state.  However, it is required in the Consented state.

(2) Yes, consent to be contacted should be captured in both the clinician invite flow as well as the self-registration flow as an actual consent in the consent database.

**Comment by b-f-chan** [comment]
#3 decided as mutually exclusive

Closing, questions answered
