### ISSUE TITLE
PI DAS - Updates to support create Participant

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#391]
Some of the create participant flow was implemented previously, but there is some remaining work needed now that we have the validation and error handling available. Some items here are TBD, and are tracked in [#388](https://github.com/ohcrn/platform/issues/388)

- [x] add delete participant endpoint
- [x] add deleteParticipant service call
- [x] migration - Participant table: update `emailAddress`, `phoneNumber` -> `participantEmailAddress`, `participantPhoneNumber`. 
- [x] migration - Participant table: add `@unique` constraint to `guardianEmailAddress`.
- [x] migration - Participant table: update `residentialPostalCode` in Participant table to be nullable
- [x] migration - Participant table: add `keycloakId` to Participant table, with `@unique` constraint
- [x] update service and router params to match all migration changes
- [x] add logs, error handling + validation to POST participants endpoint, following pattern established in ClinicianInvite flow
- [x] update swagger schemas with new schema types
- [x] update jsdocs for POST participants endpoint
- [x] update seed data

**Comment by b-f-chan** [comment]
merged, closing!
