### ISSUE TITLE
Consent DAS - Updates to support create Participant

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#392]
Some of the create participant flow was implemented previously, but there is some remaining work needed now that we have the validation and error handling available. Some items here are TBD, and are tracked in [#388](https://github.com/ohcrn/platform/issues/388)

~~- [ ] add services/delete file~~
~~- [ ] add delete participant endpoint~~
~~- [ ] add deleteParticipant service call~~
- [x] migration - remove guardianIdVerified field from participant table
- [x] migration - add consentToBeContacted to participant table
- [x] update router and service params to match migration changes
- [x] add error handling + validation to  POST participants endpoint, following pattern established in ClinicianInvite flow
- [x] update swagger schemas with new schema types
- [x] update jsdocs for POST participants endpoint
- [x] update seed data

**Comment by b-f-chan** [comment]
Merged, closing
