### ISSUE TITLE
🐛 Consent UI: "Help" Button Sizing Incorrect in Safari

### ISSUE THREAD

**Issue by mistryrn** [OHCRN/platform#396]
Investigate and fix incorrect "Help" button sizing when Consent UI is viewed on Safari (see screenshot below).

## Expected Outcome(s):
- [ ] "Help" button appears as expected on Safari, consistent with Chrome and Firefox

## Screenshot:
<img width="1324" alt="Screenshot 2024-01-25 at 3 34 54 PM" src="https://github.com/OHCRN/platform/assets/3392776/a1d1dd61-1cc3-4514-a193-5a710b20412c">

**Comment by b-f-chan** [comment]
@xusandrew can this be closed?

**Comment by xusandrew** [comment]
@b-f-chan yes

**Comment by b-f-chan** [comment]
Reviewed & merged --> Closing
