### ISSUE TITLE
Update ClinicianInvite Schema participant name fields

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#411]
As discussed in https://github.com/OHCRN/platform/issues/388, the `participantFirstName` and `participantLastName` fields should be updated to `participantOhipFirstName` and `participantOhipLastName` to be consistent with those fields in the rest of the system.

***UPDATE**
We'll also add the change to the ClinicianInvite schema to make the participant contact fields (`participantEmailAddress`, `participantPhoneNumber`) nullable, to support the work in #450 

- [ ] migration - in PI DAS to update these fields
- [ ] update fieldnames in supporting request/response types in `types` package
- [ ] update parameter names, if required, in Data Mapper and Consent-API services and routers

**Comment by b-f-chan** [comment]
@xusandrew to prioritize and complete for start of march 12 sprint
