### ISSUE TITLE
Make a test API endpoint for UI testing

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#414]
Make an endpoint for testing UI (e.g. types, error & suspense boundaries, client vs server side requests, cacheing)

- Take an API request that defines what you get back.
- Accept GET & POST requests.
- Use existing error handling middleware

Example:
- Submitting consent wizard step 2
- Submit the formData object and what you want to get back (error code? 200 success?)
- Receive expected response

**Comment by b-f-chan** [comment]
Not needed, have real API now, closing
