### ISSUE TITLE
Consent Wizard Step X: Use mock API

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#415]
- This ticket will help inform our data fetching going forward.
- Prepopulate all form fields from mock API GET request
- On form submit, make a POST request to the same mock API
- Format data for the API (no empty strings) and UI (no undefined values)
  - Verify with safeParse on form submission (temporary, for dev only)
- Add error & suspense boundaries
- Check with Patrick about loading and error UI/UX
- Investigate:
  - ~~Libraries to use? We're using Axios, is that still OK?~~ axios is fine
  - ~~Any notes on auth?~~ Ann's on it
  - ~~Cacheing~~ too early for this

**Suggestion --> Have the endpoint just take whatever request it gets and pass it back, so you can re-use it for whatever step later**

**Comment by b-f-chan** [comment]
Objective --> Mock response available for everything except Step 2

**NOTE: All work being done in NextJS API**

@samrichca to chat with @anncatton how the auth proxy works and needs to be interacted with

**Comment by samrichca** [comment]
blocked by API proxy work

**Comment by b-f-chan** [comment]
#479 is completed, this is unblocked

**Comment by b-f-chan** [comment]
Closing this ticket, we have enough work in the pipeline to not require a mock
