### ISSUE TITLE
Enforce server side only for translation functions

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#422]
We can add a package called `server-only` to the `getTranslation` file to ensure both translate functions are used only in server components. This is the recommended package in the [NextJS docs](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment) . 

This will require some rearranging of the ConsentWizard step components as well as the Versions component in the footer element: we have some server components with translation code incorrectly imported into client components, which is not a [supported pattern](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#unsupported-pattern-importing-server-components-into-client-components).

Steps:
- [ ] add `server-only` import to `src/i18n/utils/getTranslation.ts`
- [ ] `replaceParams` should be exported from its own file, so it can still be used client-side
- [ ] how we structure the consent wizard view components would need to change slightly - for example, because InformedConsentForm is a client component, ConsentStepsNavigation would need to be brought in through the `children` prop, instead of being directly imported in the file
- [ ] update the API version component, a possible solution can be found in this [draft PR](https://github.com/OHCRN/platform/pull/228)

**Comment by b-f-chan** [comment]
Reviewed & merged --> Closing
