### ISSUE TITLE
Fix homepage background image 

### ISSUE THREAD

**Issue by xusandrew** [OHCRN/platform#424]
The background image on the homepage is cropped instead of filling up the entire background:

In dev:
<img width="1634" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWhCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2dbd62444566006d6514271b251d616fc5b0932/Screenshot%202024-02-08%20at%2011.30.05%E2%80%AFAM.png" alt="Screenshot 2024-02-08 at 11.30.05 AM.png" />

Intended behaviour:
<img width="1602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWxCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f9e289706ff203c5b4c23e3afdb450fe14a2923/Screenshot%202024-02-08%20at%2011.30.25%E2%80%AFAM.png" alt="Screenshot 2024-02-08 at 11.30.25 AM.png" />

**Comment by b-f-chan** [comment]
@xusandrew can this be closed?

**Comment by xusandrew** [comment]
@b-f-chan yes

**Comment by b-f-chan** [comment]
Reviewed & merged --> Closing
