### ISSUE TITLE
Create Mockups for Maintenance Banner

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#433]
Create mockups for the site's standard maintenance banner

Use ARGO's standard model as a reference, we need the usual 3 states:

- INFO
- WARNING
- CRITICAL

**Comment by patrickdsantos** [comment]
Mocks are available within the MVP Figma File: https://www.figma.com/file/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?type=design&node-id=2%3A11926&mode=design&t=6CAmRKylnNqR4Eww-1

The banner will take up the full width of the devices screen. 

<img width="1168" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFJWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--928ebac878d8dc66c4ad470206918444945e4c20/CriticalBanner.png" alt="CriticalBanner.png" />
<img width="1168" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67aa4dfdb017e28c02aa0d0fd85d994fb4ae73eb/WarningBanner.png" alt="WarningBanner.png" />
<img width="1168" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4881d20bc8a7421fe6677a3be19fde9246b2789d/InfoBanner.png" alt="InfoBanner.png" />
