### ISSUE TITLE
Add secrets to Vault for Keycloak auth

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#446]
Next-Auth and Keycloak require secret values, they will need to be added to Vault:

`AUTH_KEYCLOAK_SECRET`
`AUTH_SECRET`
`TOKEN_ENCRYPTION_KEY`

`TOKEN_ENCRYPTION_KEY` will have a default value set until this is added, because a missing value breaks the consent-ui build. The other 2 values can be left blank without affecting the build; however, the login flow will not work without them.
Be sure to remove the default value from consent-ui AppConfig once this is completed.

**Comment by b-f-chan** [comment]
Reviewed, merged, closing
