### ISSUE TITLE
Nginx error when login initiated with an existing Keycloak session

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#447]
If a login attempt is made from the Consent UI, and there is an existing session in Keycloak, the request to the Keycloak auth endpoint results in an Nginx server error.

To reproduce:
- log in on the consent-ui
- delete the next-auth cookies in the browser application tab
- login again from the ui
- browser navigates to the Keycloak domain and will show an Nginx error

**Comment by b-f-chan** [comment]
Should no longer be an issue once cookie size is fixed

**Comment by anncatton** [comment]
Confirmed in dev, this issue is related to the large cookie size and the nginx reverse proxy setup. User data will be removed from the next-auth session in #502 , so this should be resolved once the work is completed. Closing as no further investigation is needed.
