### ISSUE TITLE
Add Missing Fields to Data Model v5.0

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#458]
Add the following missing fields to Data Model v5.0:

- assentFormIdentifier
- vitalStatus
- hasOhip

### PI DAS
- Participant table
  - `assentFormIdentifier` (optional, string)
  - `hasOhip` (required, boolean, default `true`)
- Clinician Invites table
  - `assentFormIdentifier` (optional, string)
  
### PHI DAS
- Clinical Profile table
  - `vitalStatus`

## Properties
`vitalStatus` requires an enum of possible values, @b-f-chan to provide

**NOTE: Detailed properties to be added to this ticket (which DASes @mistryrn, what properties @b-f-chan)**

**Comment by xusandrew** [comment]
@b-f-chan Can you provide the enum for the `vitalStatus` field?

**Comment by b-f-chan** [comment]
Reviewed & merged --> Closing
