### ISSUE TITLE
Clinician Invite Page --> API Hookup

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#459]
Hookup the clinician invite page to the API

Additional tasks:

- [ ] Add loading spinner to form based on Patrick's mockups

**Comment by samrichca** [comment]
blocked by API proxy work

**Comment by b-f-chan** [comment]
#479 is complete, this ticket is unblocked

**Comment by b-f-chan** [comment]
@samrichca - Please try this ticket with Server Actions now that we have made the decision

**Comment by b-f-chan** [comment]
Blocked by both #480 and #477

**Comment by samrichca** [comment]
don't include assent form upload flow or identifier
