### ISSUE TITLE
Alignment/style fixes for Date Picker

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#471]
The date picker is displaying with some alignment issues on the tooltip arrow and when it displays next to the footer on the Registration page.

When displaying at the top of the input:

 <img width="670" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXZCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02388c547a6c0a4efa265543aef949edd22c7302/date_picker_alignment_top.png" alt="date_picker_alignment_top.png" />

When displaying at the bottom of the input:

<img width="774" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTNCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d147433cc65b8705d0da885ffe329573452b4d5/date_picker_alignment_bottom.png" alt="date_picker_alignment_bottom.png" />

**UPDATE:**
Let's also add the Month and Year selectors: https://reactdatepicker.com/#example-year-select-dropdown
- [ ] add `showMonthDropdown`
- [ ] add `showYearDropdown`

**Comment by anncatton** [comment]
Below: 
<img width="433" alt="image" src="https://github.com/OHCRN/platform/assets/5624601/4505905f-ab3a-452e-b412-efe22267106d">

Above, you can see there is another week that should display, plus the bottom border of the picker shows:
<img width="398" alt="image" src="https://github.com/OHCRN/platform/assets/5624601/f487a359-dd17-4ba0-bf27-2c0d631bd486">

**Comment by samrichca** [comment]
I also see it getting cutoff by the footer. maybe increasing the z-index would work?

**Comment by b-f-chan** [comment]
Reviewed & merged --> Closing
