### ISSUE TITLE
Update Types for AssentFormIdentifier Fields

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#480]
Update types for assentFormIdentifier fields (both participant and clinician invite)

- [x] ~~Participant -> add `hasOhip` to base type that relates to PI DAS, update tests~~ Update `ParticipantIdentification` and related tests, and the create participant *Response* types for Data Mapper and PI DAS. The `hasOhip` field has a default value in the db when the participant record is created, so we don't need to have it as part of the CreateParticipant Request schemas
- [x] ClinicianInvite -> add `AssentFormIdentifier` to `InviteParticipantFields` base type OR separately to PIClinicianInvite types as needed, update tests
- [x] ClinicalProfile -> add `VitalStatus` to base type, update tests
- [x] the `assentFormIdentifier` is only required for participants with the consentGroup `GUARDIAN_CONSENT_OF_MINOR_INCLUDING_ASSENT`. So we should add refinement logic to ensure this field is populated when needed, and not present when not required. This would be similar to how we're handling the guardian vs participant contact info
- [x] unit tests for this refinement function, like we have in `conditionalFields.spec.ts` and `dateOfBirth.spec.ts`
- [x] schema integration tests with the refinement, similar to what we have in [ClinicianInvite,spec.ts](https://github.com/OHCRN/platform/blob/develop/packages/types/tests/entities/ClinicianInvite.spec.ts#L83)
- [x] the `PICreateParticipantResponse` and `PIClinicianInviteResponse` types need to handle the possibly null value for assentFormIdentifier, because it is an optional field. The DB will return null if no value was provided, and this needs to be coerced into undefined when the PI DAS service receives the response from Prisma. The subsequent responses from then on do not require any further coercion. An simple example can be found [here](https://github.com/OHCRN/platform/pull/assentFormIdentifier) . There's also some notes about it in the [shared-docs readme](https://github.com/OHCRN/platform/blob/develop/docs/shared-types.md#converting-null-values-to-undefined)
- [ ] verify create ClinicianInvite and create Participant flows work with the `assentFormIdentifier` added, to ensure request and response types are working as expected.

**Comment by xusandrew** [comment]
Updated the related types to #458

**Comment by xusandrew** [comment]
clinicianInvite flow works, work on tests
