### ISSUE TITLE
Research How Next.js Server Actions Work and their Pros/Cons

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#497]
Research how Next.js Server Actions work and their pros & cons

We need to determine if it is worthwhile for us to user Next.js Server Actions instead of Server Components for data fetching moving forward

## Expected Output ##

Short wiki page describing:

1. How Server Actions Work
2. Pros & cons of using them

**Comment by xusandrew** [comment]
TODO: Get sample implementation of server actions to do onSubmit and data fetch in forms

**Comment by xusandrew** [comment]
Write WIKI page in Technical Design/Research
