### ISSUE TITLE
Researching Keycloak to Meet OHCRN Requirements

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#50]
Researching Keycloak to Meet OHCRN Requirements, including:

- [x] (1) Customizing the Keycloak login/registration page
- [x] (2) Research/config for the Google OAUTH plugin
- [x] (3) Email setup to send registration emails out (and to resend)
- [x] (4) Change password, reset password

**EXIT CRITERIA:**

- [x] Wiki page summarizing the research results

**Comment by mistryrn** [comment]
Reviewed the wiki page (https://wiki.oicr.on.ca/display/OHCRN/Keycloak) and it looks good! I approve ✅

Some potential resources for the SMS 2FA investigation:
- https://github.com/dasniko/keycloak-2fa-sms-authenticator
- https://www.n-k.de/2020/12/keycloak-2fa-sms-authentication.html

**Comment by b-f-chan** [comment]
Wiki looks good, additional investigations will be done in separate tickets, closing
