### ISSUE TITLE
Add Signed By Line & Timestamp to E-Signature

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#541]
Add the signed by line and the timestamp to the E-Signature on the consent PDF

Use the design in @patrickdsantos mockups

**Comment by samrichca** [comment]
mockup https://www.figma.com/file/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?type=design&node-id=3809-21105&mode=design&t=T5rDS0hMx2qeF7LQ-0

**Comment by samrichca** [comment]
examples

![image](https://github.com/OHCRN/platform/assets/3540896/50f3a970-baa7-454e-9444-0e15fa54fa61)
- english
- guardian consent group
- long name, wrapped on 2 lines
- participant name added

![image](https://github.com/OHCRN/platform/assets/3540896/0e041a4b-7d06-46bb-800b-2fc4ab99cd24)
- french
- participant consent group
