### ISSUE TITLE
Create Mockup for 2FA Method (Mobile # or Email)

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#545]
Create a mockup showing how users can indicate the 2FA method

We will support 2FA via mobile # or email

Not all users will have mobile, so we need ability to indicate either they choose email or we don't have a mobile #

**Requirements:**

- [x] On registration, add check box to confirm if phone number is a mobile number
- [x] Mockup the Keycloak 2FA screen:
    - [x] Text box to enter the code
    - [x] Alternate button/function to retry/resend to same mobile #
    - [x] Alternate button/function to instead send to email

**Comment by patrickdsantos** [comment]
@b-f-chan @anncatton 
New mockups available below and on the Figma MVP file!

Registration:
<img width="726" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32a18880367a39b0a597a3651f00c603c1105eea/ParticipantRegistration.png" alt="ParticipantRegistration.png" />
<img width="632" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjZGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eec2a39d412a89d46cb8c7d1ec715655887968db/ParticipantRegistration.png" alt="ParticipantRegistration.png" />

Keycloak:
<img width="1413" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2603fb09ceb72b5a7d968629f15071e08ca8ce16/Keycloak.png" alt="Keycloak.png" />

<img width="1413" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36eec371cf0112e5efe2aafb61c56663190be997/Keycloak-1.png" alt="Keycloak-1.png" />
