### ISSUE TITLE
Auth: Add ParticipantID to Session

### ISSUE THREAD

**Issue by mistryrn** [OHCRN/platform#566]
Consume `/user` endpoint and retrieve `participantId` for user based on `keycloakId`, store in session, update API auth middleware to consume `participantId` from session

## Consent API
- [ ] add `participantId` to request type declaration
- [ ] inside handler: extract `participantId` from header information

## Consent UI
- [ ] add `participantId` to session from `/user` endpoint

**Comment by b-f-chan** [comment]
Done, closing
