### ISSUE TITLE
Modify middleware apiProxy setup to use route handler

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#571]
The api proxy implemented in #521 as part of the middleware is not able to access cookies, so the next-auth session is always `null`. There is also an issue with using the `crypto` module, due to different runtimes in [NextJS](https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes#use-cases).

There may also be issues using a database adapter for handling auth session (targeted in https://github.com/OHCRN/platform/issues/502), combined with the middleware proxy setup, because of the Edge runtime: https://github.com/vercel/next.js/discussions/38989

Solution:
We want to keep the behaviour of the apiProxy to allow for streaming data (for file upload), but will move the logic into an app route handler. The auth session was accessible when a route handler was implemented in [#370](https://github.com/OHCRN/platform/pull/426).

**Comment by b-f-chan** [comment]
Done, closing
