### ISSUE TITLE
Add `selfReportedPrimaryCancerDiagnosis` enum field to PHI DAS Prisma schema + Zod type 

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#579]
Update PHI DAS schema to include `selfReportedPrimaryCancerDiagnosis`:
- [ ] add `PrimaryCancerDiagnosis` enum type to prisma schema file
- [ ] add `selfReportedPrimaryCancerDiagnosis` field to `ClinicalProfile` table, will be `nullable`
- [ ] add `PrimaryCancerDiagnosis` enum type to `types/entities/fields`. This type can be reused for the `primaryCancerDiagnosis` in `Diagnosis` table

**Comment by b-f-chan** [comment]
Done, closing
