### ISSUE TITLE
Update Mocks for Optional Inputs

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#593]
There's a few optional inputs that need updating in the mocks, they currently don't exist

- [x] On Step 2 of the Consent Wizard, a participant can choose `PREFER_TO_SELF_IDENTIFY` for the Gender selection. We need to add an optional text input for the participant to enter their `selfIdentifiedGender` to the Mocks.

- [x] On Step 2, if `Personal History of Cancer` is `No`, need to hide drop-down for them to select their self-reported cancer diagnosis/primary site

**Comment by patrickdsantos** [comment]
Updated the style guide to include the scenarios explained in the ticket summary above. Screenshot below:

<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWZTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--101140f9327ed5a174f2dfbc4e26c73659cdf9d6/Screenshot%202024-07-11%20at%201.19.58%E2%80%AFPM.png" alt="Screenshot 2024-07-11 at 1.19.58 PM.png" />


Also accessible in the MVP Figma file under "Style Guide": https://www.figma.com/design/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?node-id=1-11&t=rq3twPq0kbdTnoxc-1
