### ISSUE TITLE
Create GET Endpoint for File Access

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#609]
Create the GET endpoint for file access, currently it is missing (we only have POST)

Result of this is we can then store the proper images for the e-signature

**Need specific set of access rules:**

- Who are the users who have access?
- What files can those users get access to?

**Current scope**:

Just one use case right now:

- [ ] System retrieving generated e-signature image from the backend, so that UI can generate consented PDF on the fly 
- [ ] File types --> PNG only type supported

**Endpoint details**:

DEV to add

**Dependency**:

- Need ticket to change database to not store image as Base64 string, but as actual image

**Comment by joneubank** [comment]
After reviewing the e-signature process, we determined that it is completely feasible to store the signature image content as a Base64 encoded string inside postgres. As a result, there is no need to create and save an image file in an external system. This has the advantage of keeping the original signature image alongside the DB record of their signature, meaning there is no extra work required to keep the images in object storage synced to their esignature record. We no longer need to handle edge cases such as failing to find/download the image from object storage when retrieving their image details.

As a result, we won't need to do this work to read/write e-signature image data from object storage.
