### ISSUE TITLE
Improve PDF generation

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#628]
Improve PDF generation when backend is complete.

- Use progress endpoint to determine if PDF is ready.
- Use /participants/{id} to fetch user data.
- Pick a size/ratio for signature images.
- Update Consent Wizard step 5 to limit the size of the signature field.
- Implement real base64 signature images in the PDF.
- Also need to test guardian flow

**Comment by b-f-chan** [comment]
Closing as all these tasks are either completed or to be done in separate tickets
