### ISSUE TITLE
Consent UI: Modal "Leave Page" Button Redirects to Stale State

### ISSUE THREAD

**Issue by mistryrn** [OHCRN/platform#632]
The current route change triggered by the "Leave Page" button on the "Would you like to leave this page?" modal does not re-trigger the GET requests on a Consent Wizard step.

For example, on Step 5, after clicking the "Previous" button to trigger the "Would you like to leave this page?" modal and clicking "Leave Page", you will be taken back to Step 4 in a **stale state**.

To verify this, make a change on Step 4, go to Step 5, then go back to Step 4 via the "Leave Page" button. When Step 4 loads, you will see the previous state of the step, not what it was just changed to.

![Screenshot 2024-05-17 at 2 29 08 PM](https://github.com/OHCRN/platform/assets/3392776/fa7868f8-f658-46cd-8464-564a0af9e456)

**Comment by b-f-chan** [comment]
Closing, covered by the next JS caching issue ticket
