### ISSUE TITLE
Create Mockups for "Try Again Later" Scenario

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#665]
Create mockups for "Try Again Later" scenarios, basically system and/or unknown failures in these areas:

(1) Clinician invite
(2) Registration
(3) Consent wizard

**Comment by patrickdsantos** [comment]
New error message mockups below. Also available in MVP Figma file: https://www.figma.com/design/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?node-id=4081-15435&t=m8O3eYydGIKZWrbs-1

<img width="395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkpPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68b069bcdcc970253f364e829d4059e4db56d5e6/consent_error.png" alt="consent_error.png" />

<img width="554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk5PQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac828a17f334b83ff7f22d4f445eea960c3bd72d/Clinician_error.png" alt="Clinician_error.png" />

<img width="870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlJPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f5300c10cca4bcd68ed0b84b7e97c55438d8a63/participant_error.png" alt="participant_error.png" />

**Comment by patrickdsantos** [comment]
@b-f-chan here's the new mocks for the error messages. Let me know what you think about the copy! (wondering if that last phrase "If you continue to experience difficulties, contact our support team for assistance." makes sense. Thinking it would link to the coordinator's email. I can also remove it if we don't want people emailing Elif for these types of errors.

**Comment by patrickdsantos** [comment]
Remove CTA's from modals but keep links

**Comment by patrickdsantos** [comment]
<img width="395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmh6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6464022c228ac7f71005ffc258446fc9ec621d4/Error-Message.png" alt="Error-Message.png" />
<img width="554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmx6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a30abe8a51dd92559f069fb70c29181c9daa042c/ClinicianRegistration.png" alt="ClinicianRegistration.png" />
<img width="870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnB6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66bae46e0c3eeecf55b6e6de602d51fee141be39/Oops-Error.png" alt="Oops-Error.png" />
