### ISSUE TITLE
Update Mockup to Allow Multiple Self-Reported Cancer Diagnoses Entries

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#668]
Update the mockups for Consent Wizard Step 2 to allow participants to select multiple self-reported primary cancer diagnoses

**Comment by patrickdsantos** [comment]
Updated the style guide with what selecting multiple items within a dropdown looks like. Screenshot available below and within the MVP Figma file under Style Guide Page: https://www.figma.com/design/uft9F45tddCba46xnL4Tfg/OHCRN%2FDev%2FMVP?node-id=1-11&t=ATfxGXY0DBaXnEWP-1

<img width="909" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzAyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b003631882c1ac540766fede03aec696b9b4c151/Screenshot%202024-06-04%20at%203.13.25%E2%80%AFPM.png" alt="Screenshot 2024-06-04 at 3.13.25 PM.png" />
