### ISSUE TITLE
Loosen Restrictions on Dev Environment Once QA is Deployed

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#683]
**NOTE: DON'T NEED IMMEDIATELY - To be completed after QA is deployed and tested**

Loosen Restrictions on Dev Environment Once QA is Deployed:

- [x] Remove Networking Policies that prevent access to Swagger for Data Mapper and DASes in Dev 🙏
- [x] Create PR for DevOps to execute this work

**Comment by mistryrn** [comment]
Relevant PR in infra repo: https://github.com/OHCRN/infra/pull/42
