### ISSUE TITLE
Stop Using Base64 String to Store E-Signature

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#700]
Currently we are storing e-signatures as Base64 strings.

Once the file upload API endpoint is completed, we should switch to uploading the actual image file

**Comment by samrichca** [comment]
Additional tasks:
- Get the PNG from an API endpoint
- Render the PNG in the PDF

These should be quick changes, but if not, make additional tickets.

**Comment by b-f-chan** [comment]
No longer required, Jon was OK with our Base64 string implementation, closing
