### ISSUE TITLE
Migrate Axios to fetch - consent UI -> Keycloak issuer

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#708]
For Keycloak issuer requests in consent UI:
- Migrate Axios requests to fetch in order to use Next's cache & revalidation features
- Ensure data is being updated after mutations, when navigating between pages
  
Original issue: #652

Note: The logout request to Keycloak is using a standalone axios instance, should be able to combine that with the client that will be created here.

**Comment by b-f-chan** [comment]
Closing, no longer required
