### ISSUE TITLE
Transition from `fetch` to `axios` in Data Mapper

### ISSUE THREAD

**Issue by mistryrn** [OHCRN/platform#72]
Switch HTTP requests in Data Mapper from using `fetch` to using `axios`
- https://axios-http.com/

Additionally, take advantage of the `Axios Instance` to avoid repeatedly setting things like Headers in each request:
- https://axios-http.com/docs/instance

Exit Criteria:
- [x] Add the `axios` package to Data Mapper
- [x] Create a shared axios instance for the Data Mapper with default headers such as content-type
- [x] Switch all `fetch` requests in the Data Mapper to use `axios` instead
    - Note: these can be found by searching for the following `TODO` item: `// TODO: use axios instead of fetch`

**Comment by b-f-chan** [comment]
Completed, merged, closing
