### ISSUE TITLE
Consent Portal - Complete Mocks for Change Password/Change Email Flows

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#727]
Based on the chosen flow in #352, need to update the mocks to include the forms for a User changing their password or their email. The wiki for this topic has been updated with flow details and requirements.

- [x] password form should include the same validation messaging as shown in Registration
- [x] email change will include form fields for the user to confirm OTP codes sent to the old and new email addresses, with instructions on how to proceed + confirm the change

@patrickdsantos to fill in details as necessary

**Comment by b-f-chan** [comment]
Reviewed, closing
