### ISSUE TITLE
Complete Styling for Language Toggle

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#73]
Complete styling for the language toggle/button based on Patrick's UI/UX style guide when ready

For example, things like hover states, colours, etc

**Exit Criteria:**

- [x] Language toggle is styled according to the UX style guide

**Comment by b-f-chan** [comment]
@alyssadsouza - Please confirm if already

**Comment by alyssadsouza** [comment]
Completed in [#57](https://app.zenhub.com/workspaces/ohcrn-63ce4baf33421e00316b1f7b/issues/gh/ohcrn/platform/57)

**Comment by b-f-chan** [comment]
Confirmed with @alyssadsouza PR review done.  We will test this more fully when actual Portal with UI pages is deployed to QA.  Closing.
