### ISSUE TITLE
Header: Add link to FAQ

### ISSUE THREAD

**Issue by samrichca** [OHCRN/platform#853]
- [ ] On the "Help" button, add a link to https://ohcrn.ca/faq/
- [ ] Link should open in a new tab

<img width="347" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c16cef8bd72dbe08d2a7a2a03528db14f22242e/image.png" alt="image.png" />

**Comment by shailikadakia-oicr** [comment]
@samrichca I think we can mark this complete [https://github.com/OHCRN/platform/pull/835](https://github.com/OHCRN/platform/pull/835). Confirmed it is correctly working in QA

**Comment by samrichca** [comment]
closing, this work was done already
