### ISSUE TITLE
Design File Storage Strategy

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#90]
Strategy for:

- Assent form PDFs
- Genetic test / molecular report PDFs
- Pathology report PDFs
- Pedigrees
- Downloadable consent form with e-signature
- Other PDFs (supporting docs at the CRC's discretion)
- Ability to track file uploads and/or deletes in the change log --> Speak to @anncatton about if/how they did this in DACO

**EXIT CRITERIA:**

- [x] Wiki page documenting our file storage strategy for the above file types and how it impacts our architecture

**Comment by b-f-chan** [comment]
@b-f-chan --> Get sample of Assent Form from Lauren

**Comment by b-f-chan** [comment]
Need file samples, file size estimates, and frequency of upload and retrieval

**Comment by mistryrn** [comment]
File Storage Wiki: https://wiki.oicr.on.ca/display/OHCRN/File+Storage+Strategy

**Comment by b-f-chan** [comment]
Need @joneubank final review, finish in new year

**Comment by b-f-chan** [comment]
Reviewed by @joneubank, feedback incorporated
