### ISSUE TITLE
Footer, Header elements should be sticky

### ISSUE THREAD

**Issue by anncatton** [OHCRN/platform#99]
Update Footer and Header elements to `sticky`. The footer will only be sticky if there is minimal content, see this for a reference on the recommended approach:
https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers

**Comment by b-f-chan** [comment]
@b-f-chan @patrickdsantos to test on QA:
https://consent-ui.dev.ohcrn.cancercollaboratory.org/en/register

**Comment by patrickdsantos** [comment]
Footer seems good to me! But the header doesn't appear at the top when the window is full screen.

**Comment by b-f-chan** [comment]
@samrichca can this be closed?
